name: xkegs # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.05' # just for humans, typically '1.2+git' or '1.3.2'
summary: Apple IIgs emulator
description: |
  Apple IIgs emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  xkegs_icon.png
title: xKegs

apps:
  xkegs:
    command: xkegs
parts:
  xkegs:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      xkegs: build/
      xkegs.1: man/man1/

architectures:
  - build-on: amd64

